import { Box, Container, Stack, Text } from '@chakra-ui/react';
import { Link, Outlet } from 'react-router-dom';
import Content from '../components/Content';
import Logo from '../components/Logo';
import Navigation from '../components/Navigation';

export default function HomeLayout() {
  return (
    <>
      <Container maxWidth={'container.xl'} paddingY={16}>
        <Stack spacing={4} alignItems={'center'}>
          <Box width={250} margin={'0 auto'}>
            <Logo />
          </Box>
          <Box w={'100%'}>
            <Navigation />
          </Box>
          <Box w={'100%'}>
            <Content>
              <Outlet />
            </Content>
          </Box>
          <Text
            display={'block'}
            color={'whiteAlpha.500'}
            textAlign={'center'}
            maxWidth={800}
            margin={'0 auto'}>
            For more information, feel free to visit our info page{' '}
            <Text color={'blue.300'} display={'inline'} opacity={0.8}>
              <Link to={'/info'}>here</Link>
            </Text>
            . Again, we expressly disclaim any liability for any content displayed on this
            website that is generated by users.
          </Text>
        </Stack>
      </Container>
    </>
  );
}
